// Auto-generated by SPT.BridgeUI.TypeGen
// Do not edit manually - regenerate using: spt-bridgeui-typegen

export interface ApiResponse<T> {
  success: boolean;
  message?: string;
  data?: T;
}

export interface SPTClientMod {
  guid?: string;
  forceGuid?: string;
  name?: string;
  modVersion?: string;
  forceModVersion?: ForceModVersion;
  visible?: boolean;
}

export interface SPTForgeMod {
  id: number;
  guid?: string;
  name?: string;
  teaser?: string;
  thumbnail?: string;
  detail_url?: string;
  sptVersions?: SPTForgeModVersion[];
}

export interface SPTForgeModVersion {
  id: number;
  version?: string;
  spt_version_constraint?: string;
  fika_compatibility?: string;
}

export interface ForgeModUpdate {
  guid?: string;
  name?: string;
}

export interface SPTServerMod {
  guid?: string;
  forceGuid?: string;
  name?: string;
  author?: string;
  modVersion?: string;
  forceModVersion?: ForceModVersion;
  sptVersion?: string;
  visible?: boolean;
}

export interface SptModResponse {
  sptClientMods?: Record<string, SPTClientMod[]>;
  sptServerMods?: SPTServerMod[];
  sptForgeMods?: SPTForgeMod[];
}

export interface HideClientMod {
  clientName?: string | unknown;
  guid?: string | unknown;
}

export interface HideServerMod {
  guid?: string;
}

export interface ForceModVersion {
  modVersion: number;
  forceVersion: number;
}

export const ModType = {
  SERVER: 0,
  CLIENT: 1,
} as const;
export type SptModType = typeof ModType[keyof typeof ModType];

export interface ForceModVersionRequest {
  modType: SptModType;
  clientName?: string;
  guid?: string;
  modVersion?: number;
  forceVersion?: number;
}

export interface ForceModGuidRequest {
  modType: ModType;
  clientName?: string;
  guid?: string;
  forceGuid?: string;
}