import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.17.3',
  date: '2025-12-25T16:44:20.152Z',
};
export default meta;
