import type MetaInterface from '@/interfaces/MetaInterface';

// This file is auto-generated by the build system.
const meta: MetaInterface = {
  version: '1.17.3',
  date: '2025-12-27T11:47:34.744Z',
};
export default meta;
